### ISSUE TITLE
Using @gdoc in PlusKit

### ISSUE THREAD

**Issue by firedude2894** [yourhead/pluskit#9]
I tried using the @gdoc feature in PlusKit and cannot get it to work.
Should it still be working in this version?
RW6 6.3.8
Stacks 3.0.5
PlusKit 3.0.0
page is PHP

Here are the variations I tried, all with no success.
@gdoc((key:1x5XrmpDnlLc7KyKqZfkTR-afsbTHoHh0ppocTfmigb4?edit))
@gdoc((1x5XrmpDnlLc7KyKqZfkTR-afsbTHoHh0ppocTfmigb4/edit))
@gdoc((1x5XrmpDnlLc7KyKqZfkTR-afsbTHoHh0ppocTfmigb4/edit?usp=sharing))
@gdoc((key: 1x5XrmpDnlLc7KyKqZfkTR-afsbTHoHh0ppocTfmigb4/edit?usp=sharing))

**Comment by yourhead** [comment]
the problem here are your google urls.

this is what you have (broken):

```
@gdoc((key:1x5XrmpDnlLc7KyKqZfkTR-afsbTHoHh0ppocTfmigb4?edit))
```

change to this (works):

```
@gdoc((key:1x5XrmpDnlLc7KyKqZfkTR-afsbTHoHh0ppocTfmigb4))
```

**Comment by yourhead** [comment]
also:  when submitting bugs please include only those components that necessary for demonstrating the bug.  in this case it's best to avoid using Stacks since that only tends to complicate matters.  use a plain vanilla Styled text page.

here is a screenshot of the a plain vanilla styled text page with the above working document:

![gdoc import](https://dl.dropboxusercontent.com/u/433436/Pasted_Image_4_9_16__3_42_PM.png)

**Comment by firedude2894** [comment]
Thanks for the help Isaiah.

I have done as you suggested and added the correct string of code to a plain styled text page at: 
https://www.restorationcs.com/supplies/ https://www.restorationcs.com/supplies/

The page works in view only mode, but when I add the ?edit modifier to the end of the string, the gdoc no longer displays.

Brad Miller
firedude2894@mac.com mailto:firedude2894@mac.com

**Comment by yourhead** [comment]
I'm not too knowledgeable on the URL schemes employed by google, but I would`?edit` parameter is used when you are signed in and editing the document.  So that parameter doesn't seem like it makes sense to me.  I'm not sure why you've added it here -- but it seems to me that you probably shouldn't.  If you are doing so for some specific reason and you think that's a bug in PlusKit -- then please provide detail about that.

Until then, this seems to work as expected, so I'm leaving the bug closed.

**Comment by firedude2894** [comment]
Dang it!
I misunderstood John’s instructions on the PlusKit video, titled Pluskit_Intro.mov. At the 12:30 mark in the video, John says to add ?edit to the end of the URL for the ability to edit. I mistakenly added it to the @gdoc command like this: @gdoc((key:1x5XrmpDnlLc7KyKqZfkTR-afsbTHoHh0ppocTfmigb4?edit)) This was wrong. I am reprimanding myself right now!

So, I instead added ?edit to the end of the URL at
https://www.restorationcs.com/supplies/ https://www.restorationcs.com/supplies/
which looks like this:
https://www.restorationcs.com/supplies/?edit https://www.restorationcs.com/supplies/?edit
Doing so give me the EDIT tab at the bottom of the page, but takes me to the Google Doc page where I am unable to edit the Doc.

This makes it difficult for me to tell if PlusKit is working properly or not. Maybe it is only the ?edit command that is no longer working with the updated version of Google Docs. I also tried adding edit?usp=sharing to the end of the URL since this seems to be what Google Docs is using for an editable Doc, but this does not work either.

The full URL that Google Docs gives for an editable doc is:
https://docs.google.com/document/d/1x5XrmpDnlLc7KyKqZfkTR-afsbTHoHh0ppocTfmigb4/edit?usp=sharing

Does this help?

Either way, appending the URL with ?edit like John suggests does add the edit tab to the bottom of the screen, but does not allow editing the Doc once the edit tab is clicked on.

**Comment by yourhead** [comment]
I'm afraid you've far surpassed my expertise with Google docs.  As such I'll probably only lead you in the wrong direction...   so I'm going dos suggest you refer to the google docs on how best to link to the edit page.

However, that link is just that:  it's merely a link -- and what that link is, how it looks and behaves...  that's entirely at the discretion of Google, it really has nothing to do with the functionality of PlusKit.

However I'd probably caution that Google does tend to change their URL schemes and APIs more than just about anyone (OK, Yahoo takes the 1st prize here) and that many of LogHounds original FAQs, Docs, and videos are now quite old.  It's very possible that the link to the Edit document has changed since John made that video.  We're attempting to update some of the support documents, but I'd say mostly just be aware that Your-Milage-(AND URLs)-May-Vary.  ;-)

**Comment by firedude2894** [comment]
A kind thanks to you Isaiah. I will do my best!

Brad Miller
firedude2894@mac.com mailto:firedude2894@mac.com
